### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Lucas-Fonte** [Lucas-Fonte/aws-ecs-express-app#1]
## TODO

- [x] Add Authorization token, to api and documentation
- [x] Add partner creation validation
- [x] Add `tests`
- [x] Fix mongoose connect issue
- [x] Fix swagger documentation
- [x] Homepage as README, redirect traffic within IP
- [x] Homolog the whole thing
- [x] (Optional) Add CI / Tests to application
- [x] (Optional) Add custom domain
- [ ] (Optional) Add a load balancer
- [ ] (Optional) Secure connection
- [ ] (Optional) Monitoring
- [ ] (Optional) Replace project URL, maybe I'll deploy it to Heroku as well due to cost
